export const LOAD_MESSAGES_SUCCESS  = 'LOAD_MESSAGES_SUCCESS';
export const REQUEST_SAVE_MESSAGE   = 'REQUEST_SAVE_MESSAGE';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const STORE_LAST_LOCATION    = 'STORE_LAST_LOCATION';
export const RESET_LAST_LOCATION	= 'RESET_LAST_LOCATION';
export const REQUEST_CREATE_RSVP    = 'REQUEST_CREATE_RSVP';
export const CREATE_RSVP_SUCCESS    = 'CREATE_RSVP_SUCCESS';
export const CREATE_RSVP_FAILURE    = 'CREATE_RSVP_FAILURE';
